package security;

public enum Permiso {

	ADMINISTRADOR,
	PANADERO,
	DISTRIBUIDOR,	
	RESPONSABLE_DE_PRODUCCION,
	RESPONSABLE_DE_DISTRIBUCION,
	ENCARGADO_CLIENTES,
	RESPONSABLE_DE_STOCK,
	SUPER_USUARIO,
}
